language_mapping = {
  "arabic": "Arabic",
  "bulgarian": "Bulgarian",
  "schinese": "Simplified Chinese",
  "tchinese": "Traditional Chinese",
  "czech": "Czech",
  "danish": "Danish",
  "dutch": "Dutch",
  "english": "English",
  "finnish": "Finnish",
  "french": "French",
  "german": "German",
  "greek": "Greek",
  "hungarian": "Hungarian",
  "italian": "Italian",
  "japanese": "Japanese",
  "koreana": "Korean",
  "norwegian": "Norwegian",
  "polish": "Polish",
  "portuguese": "Portuguese - Portugal",
  "brazilian": "Portuguese - Brazil",
  "romanian": "Romanian",
  "russian": "Russian",
  "spanish": "Spanish - Spain",
  "latam": "Spanish - Latin America",
  "swedish": "Swedish",
  "thai": "Thai",
  "turkish": "Turkish",
  "ukrainian": "Ukrainian",
  "vietnamese": "Vietnamese"
}
