language_mapping = {
    "Arabic": "arabic",
    "Bulgarian": "bulgarian",
    "Chinese (Simplified)	": "schinese",
    "Chinese (Traditional)": "tchinese",
    "Czech": "czech",
    "Danish": "danish",
    "Dutch": "dutch",
    "English": "english",
    "Finnish": "finnish",
    "French": "french",
    "German": "german",
    "Greek": "greek",
    "Hungarian": "hungarian",
    "Italian": "italian",
    "Japanese": "japanese",
    "Korean": "koreana",
    "Norwegian": "norwegian",
    "Polish": "polish",
    "Portuguese": "portuguese",
    "Portuguese - Brazil": "brazilian",
    "Romanian": "romanian",
    "Russian": "russian",
    "Simplified Chinese": "schinese",
    "Spanish - Spain": "spanish",
    "Spanish - Latin America": "latam",
    "Swedish": "swedish",
    "Thai": "thai",
    "Traditional Chinese": "tchinese",
    "Turkish": "turkish",
    "Ukrainian": "ukrainian",
    "Vietnamese": "vietnamese"
}
